### ISSUE TITLE
Some problems in DataFixture run

### ISSUE THREAD

**Issue by fxcosta** [Aximem/Seran#1]
I was searching for projects in symfony 3 because I'm starting to learn it now and I found this very good project for those wanting to learn.

But in the setup process I had some problems mainly to run the DataFixture and i saw what's the problem. I solved based on some research. I did not fork because there is not a description of what the project is itself and I am from another country, i don't speak english or french very well, so I'll simply show snippets of code that did the DataFixture run well.

```
class LoadUser extends AbstractFixture implements OrderedFixtureInterface, ContainerAwareInterface
{
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function load(ObjectManager $manager)
    {
        // Les noms d'utilisateurs à créer
        $listNames = array('Maxime', 'Jean', 'Marc');
        $listMails = array('m.charruel@gmail.com', 'm.charruel@orange.fr', 'marc@marc.fr');

        $groupRepository = $this->container->get('doctrine')->getEntityManager('default')->getRepository('UserBundle:Group');
```
Above we get doctrine service.

```
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserGroup()
    {
        $group = $this->createQueryBuilder('g')
            ->where('g.name = :name')
            ->setParameter('name', 'user')
            ->getQuery()
            ->getOneOrNullResult();

        return $group;
    }

}
```
reference: http://stackoverflow.com/questions/29227635/no-result-was-found-for-query-although-at-least-one-row-was-expected

and finally I had to set almost all fields of the theme table to allow null because the DataFixture are not entered information for these fields.

I hope you have helped and continue to contribute to the project so that others can learn too! Thanks.

**Comment by Aximem** [comment]
Hi, 

Thanks for the feedback.

I'm learning Symfony 3 too, this project is just a way for me to have historic of what I do, there is nothing special with the project :) 

Anyway I don't really what you changed and why ?
You changed this : ->getOneOrNullResult(); ?

**Comment by fxcosta** [comment]
@Aximem exactly. according to own reference that I cited. basically the fixture gave error because the method that you use: getSingleResult() and he does not work well if this query does not return anything. To avoid this we use a method that returns a valid result or a null.

**Comment by Aximem** [comment]
Nice :) Thanks for your fix, I will include it in next commit.
